<?php
declare(strict_types=1);
header('Content-Type: application/json');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');
if(!is_file(__DIR__.'/app/config.php')){http_response_code(503);echo json_encode(['error'=>'Installation required. Open install.php.']);exit;}
require __DIR__.'/app/core.php';
require __DIR__.'/app/websites.php';
try{
 websiteSchema();hostWorkspace();
 $action=$_GET['action']??'session';
 if($action==='stripe_webhook'){require __DIR__.'/app/billing.php';webhook();}
 session_boot();$write=$_SERVER['REQUEST_METHOD']==='POST';if($write)csrf();
 if($action==='session'){ $u=user(false);$w=$u?query('SELECT * FROM workspaces WHERE id=?',[$u['workspace']])->fetch():null;respond(['user'=>$u,'workspace'=>$w?array_merge($w,['data'=>json_decode($w['data'],true)]):null,'csrf'=>$_SESSION['csrf'],'integrations'=>['billing'=>!empty(config()['stripe_secret']),'email'=>!empty(config()['mail_enabled'])]]); }
 if($action==='public')respond(publicWebsite());
 if(!$write&&$action==='connections'){$u=member();if(!in_array($u['role'],['owner','admin']))fail('Owner access required',403);respond(connectionSettings($u));}
 if($action==='image'||$action==='download'){ $id=clean($_GET['id']??'',32);$f=query('SELECT * FROM files WHERE id=?',[$id])->fetch();if(!$f)fail('File not found',404);$hw=hostWorkspace();if($hw&&$hw['id']!==$f['workspace'])fail('File not found',404);$u=user(false);$ok=$u&&$u['workspace']===$f['workspace'];if(!$ok&&$action==='image'&&str_starts_with($f['mime'],'image/')){$w=query("SELECT * FROM workspaces WHERE id=? AND status='approved'",[$f['workspace']])->fetch();if($w&&!empty(json_decode($w['data'],true)['published']))foreach(query("SELECT data FROM records WHERE workspace=? AND kind='property'",[$f['workspace']])->fetchAll() as $r){$d=json_decode($r['data'],true);if(!empty($d['published'])&&str_contains(($d['image']??'').($d['images']??''),'id='.$id))$ok=true;}}if(!$ok)fail('File is private',403);$path=config()['storage_path'].'/'.$id;if(!is_file($path))fail('File unavailable',404);header('Content-Type: '.$f['mime']);header('Content-Length: '.$f['size']);header("Content-Disposition: ".($action==='image'?'inline':'attachment')."; filename*=UTF-8''".rawurlencode($f['name']));readfile($path);exit; }
 if(!$write&&$action==='records'){$u=member();$rows=query('SELECT * FROM records WHERE workspace=? ORDER BY created DESC',[$u['workspace']])->fetchAll();foreach($rows as &$r)$r['data']=json_decode($r['data'],true);respond($rows);}
 if(!$write&&$action==='team'){$u=member();respond(query('SELECT id,name,email,role,active,created FROM users WHERE workspace=?',[$u['workspace']])->fetchAll());}
 if(!$write&&$action==='audit'){$u=member();respond(query('SELECT action,record_id,created FROM audit WHERE workspace=? ORDER BY created DESC LIMIT 100',[$u['workspace']])->fetchAll());}
 if(!$write&&$action==='admin'){admin();respond(['workspaces'=>query('SELECT id,name,slug,status,plan,subscription_status,created FROM workspaces ORDER BY created DESC')->fetchAll(),'users'=>query('SELECT id,name,email,role,active,created FROM users ORDER BY created DESC')->fetchAll()]);}
 if(!$write)fail('Unknown endpoint',404);
 if($action==='upload'){$u=member();$w=query('SELECT * FROM workspaces WHERE id=?',[$u['workspace']])->fetch();if(!entitled($w))fail('Update your subscription before uploading files.',402);$f=$_FILES['file']??null;if(!$f||$f['error']!==UPLOAD_ERR_OK)fail('Upload failed; check your PHP upload limit');if($f['size']>10*1024*1024)fail('Maximum file size is 10 MB');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);if(!in_array($mime,['image/jpeg','image/png','image/webp','application/pdf']))fail('Upload a JPEG, PNG, WebP, or PDF');$total=query('SELECT COALESCE(SUM(size),0) FROM files WHERE workspace=?',[$u['workspace']])->fetchColumn();if($total+$f['size']>500*1024*1024)fail('Workspace storage limit reached (500 MB)');$id=uuid();$dir=config()['storage_path'];if(!is_dir($dir))mkdir($dir,0700,true);if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$id))fail('Storage is not writable',500);query('INSERT INTO files (id,workspace,name,mime,size,created) VALUES (?,?,?,?,?,?)',[$id,$u['workspace'],clean(basename($f['name']),180),$mime,$f['size'],now()]);saveRecord($u['workspace'],'document',['name'=>clean(basename($f['name']),180),'fileId'=>$id,'mime'=>$mime,'size'=>$f['size']]);audit('file.upload',$id);respond(['id'=>$id,'url'=>'api.php?action=image&id='.$id]);}
 $b=body();
 if($action==='register'||$action==='login'){rate('auth:'.($_SERVER['REMOTE_ADDR']??''));$e=email($b['email']??'');$pass=(string)($b['password']??'');if($action==='register'){if(hostWorkspace())fail('Create subscriptions on the platform website',403);$name=clean($b['name']??'');if(strlen($name)<2||strlen($pass)<12||strlen($pass)>200)fail('Enter your name and a password of 12–200 characters');if(query('SELECT id FROM users WHERE email=?',[$e])->fetch())fail('Unable to create account with this email');$wid=uuid();$id=uuid();db()->beginTransaction();query('INSERT INTO workspaces (id,name,slug,data,status,plan,subscription_status,created) VALUES (?,?,?,?,?,?,?,?)',[$wid,$name,strtolower(preg_replace('/[^a-zA-Z0-9]+/','-',$name)).'-'.substr($wid,0,6),json_encode(['headline'=>'Exceptional homes. Personal guidance.','area'=>'Vancouver','email'=>$e,'published'=>false]),'pending','Professional','trial',now()]);query('INSERT INTO users (id,workspace,name,email,password,role,active,created) VALUES (?,?,?,?,?,?,?,?)',[$id,$wid,$name,$e,password_hash($pass,PASSWORD_DEFAULT),'owner',1,now()]);db()->commit();}else{$found=query('SELECT * FROM users WHERE email=?',[$e])->fetch();if(!$found||!$found['active']||!password_verify($pass,$found['password'])){usleep(200000);fail('Email or password is incorrect',401);}$hw=hostWorkspace();if($hw&&$found['workspace']!==$hw['id'])fail('Email or password is incorrect',401);$id=$found['id'];}session_regenerate_id(true);$_SESSION['user']=$id;$_SESSION['version']=hash('sha256',query('SELECT password FROM users WHERE id=?',[$id])->fetchColumn());$_SESSION['csrf']=bin2hex(random_bytes(32));audit('auth.'.$action);respond(['ok'=>true]);}
 if($action==='logout'){$_SESSION=[];session_destroy();respond(['ok'=>true]);}
 if($action==='forgot'){rate('reset:'.($_SERVER['REMOTE_ADDR']??''),5);$e=email($b['email']??'');if(empty(config()['mail_enabled']))fail('Email delivery is not configured. Contact the platform administrator.');$u=query('SELECT * FROM users WHERE email=?',[$e])->fetch();if($u&&(!hostWorkspace()||hostWorkspace()['id']===$u['workspace'])){$token=bin2hex(random_bytes(32));query('DELETE FROM resets WHERE user_id=?',[$u['id']]);query('INSERT INTO resets (id,user_id,expires) VALUES (?,?,?)',[hash('sha256',$token),$u['id'],gmdate('Y-m-d H:i:s',time()+1800)]);$link=rtrim(config()['app_url'],'/').'/index.php?reset='.$token;if(!mail($e,'Reset your password',"Use this link within 30 minutes:\n".$link,'From: '.config()['mail_from']))error_log('Estate: password reset mail was rejected by the mail server');}respond(['ok'=>true]);}
 if($action==='reset'){rate('reset-submit:'.($_SERVER['REMOTE_ADDR']??''),10);$r=query('SELECT * FROM resets WHERE id=? AND expires>?',[hash('sha256',(string)($b['token']??'')),now()])->fetch();$pass=(string)($b['password']??'');if(!$r||strlen($pass)<12||strlen($pass)>200)fail('Link expired or password is too short');query('UPDATE users SET password=? WHERE id=?',[password_hash($pass,PASSWORD_DEFAULT),$r['user_id']]);query('DELETE FROM resets WHERE user_id=?',[$r['user_id']]);respond(['ok'=>true]);}
 if($action==='enquiry'){$selected=requestWorkspace();if($selected&&$selected['id']!==($b['workspace']??''))fail('This enquiry belongs to a different website',404);rate('enquiry:'.($_SERVER['REMOTE_ADDR']??''),8);if(!empty($b['website']))fail('Invalid enquiry');$w=query("SELECT * FROM workspaces WHERE id=? AND status='approved'",[clean($b['workspace']??'',32)])->fetch();if(!$w||!entitled($w)||empty(json_decode($w['data'],true)['published']))fail('Agent unavailable',404);$e=email($b['email']??'');$name=clean($b['name']??'');if(strlen($name)<2)fail('Enter your name');$property=clean($b['property']??'');if($property){$p=query("SELECT * FROM records WHERE id=? AND workspace=? AND kind='property'",[$property,$w['id']])->fetch();if(!$p||empty(json_decode($p['data'],true)['published']))fail('Property unavailable');}saveRecord($w['id'],'contact',['name'=>$name,'email'=>$e,'phone'=>clean($b['phone']??''),'notes'=>clean($b['message']??'',3000),'type'=>($b['type']??'Buyer')==='Seller'?'Seller':'Buyer','status'=>'New enquiry','source'=>'Website','property'=>$property]);respond(['ok'=>true]);}
 $u=member();
 if(in_array($action,['domain_save','domain_verify','domain_remove','integration_save','email_test','stripe_test']))connectionAction($action,$u,$b);
 if($action==='save'){ $w=query('SELECT * FROM workspaces WHERE id=?',[$u['workspace']])->fetch();if(!entitled($w))fail('Your trial or subscription has ended. Update billing to continue editing.',402);if(!empty(config()['billing_required'])&&$w['plan']==='Starter'&&!in_array($b['kind']??'',['contact','property']))fail('This feature requires Professional or Team.',403);$id=saveRecord($u['workspace'],clean($b['kind']??''),$b['data']??[],isset($b['id'])?clean($b['id']):null);audit('record.save',$id);respond(['id'=>$id]);}
 if($action==='delete'){ $id=clean($b['id']??'');query('DELETE FROM records WHERE id=? AND workspace=?',[$id,$u['workspace']]);audit('record.delete',$id);respond(['ok'=>true]);}
 if($action==='settings'){if(!in_array($u['role'],['owner','admin']))fail('Workspace owner required',403);$name=clean($b['name']??'',150);if(strlen($name)<2)fail('Enter a business name');$d=[];foreach(['headline','bio','area','brokerage','phone','email','color'] as $k)$d[$k]=clean($b[$k]??'', $k==='bio'?2000:200);if($d['email'])$d['email']=email($d['email']);$d['published']=!empty($b['published']);$d['site_type']=($b['site_type']??'individual')==='agency'?'agency':'individual';$d['team']=validatePublicTeam($b['team']??[]);query('UPDATE workspaces SET name=?,data=? WHERE id=?',[$name,json_encode($d),$u['workspace']]);audit('workspace.settings');respond(['ok'=>true]);}
 if($action==='password'){$row=query('SELECT password FROM users WHERE id=?',[$u['id']])->fetch();$pass=(string)($b['password']??'');if(!password_verify((string)($b['current']??''),$row['password'])||strlen($pass)<12||strlen($pass)>200)fail('Check your current password and use at least 12 characters');query('UPDATE users SET password=? WHERE id=?',[password_hash($pass,PASSWORD_DEFAULT),$u['id']]);$_SESSION['version']=hash('sha256',query('SELECT password FROM users WHERE id=?',[$u['id']])->fetchColumn());session_regenerate_id(true);respond(['ok'=>true]);}
 if($action==='team_add'){ $w=query('SELECT * FROM workspaces WHERE id=?',[$u['workspace']])->fetch();if(!entitled($w)||(!empty(config()['billing_required'])&&$w['plan']!=='Team'))fail('An active Team plan is required',403);if(!in_array($u['role'],['owner','admin']))fail('Owner access required',403);$e=email($b['email']??'');$pass=(string)($b['password']??'');if(strlen($pass)<12||strlen($pass)>200)fail('Use a password of 12–200 characters');if(query('SELECT COUNT(*) FROM users WHERE workspace=?',[$u['workspace']])->fetchColumn()>=5)fail('Workspace supports up to 5 team members');if(query('SELECT id FROM users WHERE email=?',[$e])->fetch())fail('Email already registered');query('INSERT INTO users (id,workspace,name,email,password,role,active,created) VALUES (?,?,?,?,?,?,?,?)',[uuid(),$u['workspace'],clean($b['name']??''),$e,password_hash($pass,PASSWORD_DEFAULT),'agent',1,now()]);audit('team.add');respond(['ok'=>true]);}
 if($action==='team_toggle'){if(!in_array($u['role'],['owner','admin']))fail('Owner access required',403);query("UPDATE users SET active=? WHERE id=? AND workspace=? AND role='agent'",[!empty($b['active'])?1:0,clean($b['id']??''),$u['workspace']]);respond(['ok'=>true]);}
 if($action==='admin_update'){admin();if(($b['id']??'')===$u['workspace']&&($b['status']??'')==='suspended')fail('You cannot suspend your own administrator workspace.');$status=$b['status']??'';if(!in_array($status,['approved','pending','suspended']))fail('Invalid status');query('UPDATE workspaces SET status=? WHERE id=?',[$status,clean($b['id']??'')]);audit('admin.workspace.'.$status,clean($b['id']??''));respond(['ok'=>true]);}
 if($action==='checkout'||$action==='billing_portal'){require __DIR__.'/app/billing.php';billing($action,$u,$b);}
 fail('Unknown endpoint',404);
}catch(Throwable $e){try{if(db()->inTransaction())db()->rollBack();}catch(Throwable $ignored){}error_log('Estate: '.$e->getMessage());http_response_code(500);echo json_encode(['error'=>'The request could not be completed. Check the server error log or contact support.']);}
