<?php
declare(strict_types=1);
header('Cache-Control: no-store');
$configured=is_file(__DIR__.'/app/config.php');$done=false;$error='';
if($configured){require __DIR__.'/app/core.php';session_boot();try{$done=(bool)query("SELECT id FROM users WHERE role='admin' LIMIT 1")->fetch();}catch(Throwable $e){} }
if($configured&&!$done&&$_SERVER['REQUEST_METHOD']==='POST'){
 try{if(!hash_equals($_SESSION['csrf'],$_POST['csrf']??''))throw new Exception('Refresh and try again.');$key=config()['install_key']??'';if(strlen($key)<32||str_contains($key,'REPLACE_')||!hash_equals($key,$_POST['key']??''))throw new Exception('Check the installation key in app/config.php.');if(!filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL)||strlen($_POST['password']??'')<12||strlen($_POST['name']??'')<2)throw new Exception('Enter your name, a valid email, and a password of at least 12 characters.');schema();db()->beginTransaction();$wid=uuid();$id=uuid();query('INSERT INTO workspaces (id,name,slug,data,status,plan,subscription_status,created) VALUES (?,?,?,?,?,?,?,?)',[$wid,$_POST['name'],'founder-'.substr($wid,0,6),json_encode(['headline'=>'Exceptional homes. Personal guidance.','area'=>'Vancouver','email'=>$_POST['email'],'published'=>false]),'approved','Professional','trial',now()]);query('INSERT INTO users (id,workspace,name,email,password,role,active,created) VALUES (?,?,?,?,?,?,?,?)',[$id,$wid,$_POST['name'],strtolower($_POST['email']),password_hash($_POST['password'],PASSWORD_DEFAULT),'admin',1,now()]);db()->commit();session_regenerate_id(true);$_SESSION['user']=$id;$_SESSION['version']=hash('sha256',query('SELECT password FROM users WHERE id=?',[$id])->fetchColumn());header('Location: index.php?view=workspace');exit;}catch(Throwable $e){$error='Installation failed. Verify your database settings and installation key. '.$e->getMessage();}
}
?><!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Install Estate</title><link rel="stylesheet" href="assets/style.css"><body><main class="install panel"><a class="brand" href="index.php">E S T A T E<span>REAL ESTATE, REIMAGINED</span></a><h1>Your platform starts here.</h1><?php if($done):?><p>Estate is installed. The installer is locked.</p><a class="btn" href="index.php">Open website →</a><?php elseif(!$configured):?><p>Requires PHP 8.2+, PDO MySQL, mbstring, fileinfo, cURL, and MySQL 5.7+ / MariaDB 10.3+.</p><ol><li>Create a MySQL database and user in cPanel and grant database privileges.</li><li>Copy <code>app/config.example.php</code> to <code>app/config.php</code>.</li><li>Set database credentials, your HTTPS website URL, and a random installation key of 32+ characters.</li><li>Make the configured storage directory writable. Refresh this page.</li></ol><button onclick="location.reload()">Check configuration</button><?php else:?><p>Create the platform administrator. Use the private installation key you put in your configuration.</p><p class="error"><?=htmlspecialchars($error)?></p><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><label>Installation key<input name="key" type="password" required></label><label>Your name<input name="name" required maxlength="150"></label><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" minlength="12" required></label><button>Install Estate →</button></form><?php endif;?></main></body></html>
